import type { Metadata } from "next";
import "./globals.css";
import ApolloProvider from "./shared/providers/apolloProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloProvider>
        {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
