import type { Metadata } from "next";
import ApolloProvider from "../shared/providers/apolloProvider";
import './globals.css'
import { Header } from "@/widgets/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={'bg-[#708670]'} >
        <ApolloProvider>
        <Header/>
        {children}
        </ApolloProvider>
      </body>
    </html>
  );
}
